config/routes.rb
Rails.application.routes.draw do
  get "admin/index"
  resources :admin
  resources :users
  resources :urls
  resources :hits
  root "welcome#index"
  get "/index"=> "welcome#index"

  get "login" => "sessions#new", as: :login
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", as: :logout
  get "shorten" => "urls#shorten", as: :shorten
  get "/:path" => "urls#router"

end

app/models/hit.rb
class Hit < ActiveRecord::Base
  belongs_to :url, counter_cache: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
end

app/models/url.rb
class Url < ActiveRecord::Base
  has_many :hits
  belongs_to :user, counter_cache: true
  default_scope {order('created_at desc')}

  VALID_URL_REGEX = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~\/#=]{2,256}\.[a-z]{2,4}\b([-a-zA-Z0-9@:%_\+.~=#?&]*)/

  validates :url, presence: true, length: { maximum: 1000 },
                  format: { with: VALID_URL_REGEX }
                  # uniqueness: { scope: :user_id, case_sensitive: false }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :role
  has_many :urls
  has_many :hits, through: :urls
  has_secure_password

  before_save { self.email = email.downcase }
  validates :first_name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_breadcrumb :root # 'root_path' will be used as url
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :store_referrer
  include SessionsHelper
  include UrlsHelper
  
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    if !current_user
      flash[:danger] = "Ummm.. you may need to log in at this point"
      redirect_to login_path
    end
  end

  def store_referrer
    if !session[:referrer]
      referer = request.referer
      session[:referrer] = referer if referer && !referer.start_with?(Rails.application.secrets.app_url)
    end
  end
end

app/controllers/hits_controller.rb
class HitsController < ApplicationController
  before_filter :authorize
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by_email(session_params[:email])
    if user && user.authenticate(session_params[:password])
      log_in(user)
      redirect_to user_path(user)
    else
      flash[:danger] = "Login failed. Wrong username or password."
      redirect_to login_path
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  include UrlsHelper

  before_filter :authorize, :except => [:router, :create, :new, :shorten]

  def index
    add_breadcrumb :index
  end

  def new
    @url = Url.new
  end

  def create
    url = finnesse_url(url_params[:url])
    if url
      save_url url
    else
      flash[:danger] = "Please type in a url in the textbox below"
    end
    redirect_to request.referrer
  end

  def show
    @url = Url.includes(:hits).find_by(id: params[:id]) || nil
    if @url
      @url_hits = @url.hits
      add_breadcrumb :show, url_path(@url)
    end
  end

  def edit
    add_breadcrumb :edit, edit_url_path(@url)
  end

  def shorten
    @url = Url.new
    user_id = current_user.nil? ? request.remote_ip : current_user.id
    @urls =  Url.where(user_id: user_id).limit(10)
    render template: "urls/shorten"
  end

  def update

  end

  def delete

  end

  private

  def save_url url
    user_id = current_user.nil? ? request.remote_ip : current_user.id
    @url = Url.create(url: url, user_id: user_id)
    if generate_shortened_path
      save_success
    else
      save_error
    end
  end

  def save_success
    url = full_url(@url)
    @current_user.reload if @current_user
    respond_to do |format|
      format.html do
        flash[:success] = "Shortened url: <a href=\"#{url}\">#{url}</a>"
        redirect_to :shorten if !@current_user and return
      end
      format.js # {render 'create.js'}
    end
  end

  def save_error
    respond_to do |format|
      format.html do
        flash[:danger] = "Ummm...seems your url #{@url.errors.messages[:url][0]}. Cross-check, then try again."
        redirect_to :shorten if !@current_user and return
      end
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, :except => [:new, :create]

  def index
    @url = Url.new
  end

  def new
    redirect_to login_path
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome #{user_params[:first_name]} to lycent. Start shortening!"
      redirect_to user_path(@user)
    else
      flash[:danger] = "One or more required fields are missing"
      redirect_to login_path
    end
  end

  def show
    puts "gets to users#show"
    @user_urls = @current_user.urls || {}
    @total_hits = 0
    @user_urls.each { |url| @total_hits += (url.hits_count || 0) } if @user_urls && !@user_urls.empty?
    puts "gets all params from users#show"
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @url = Url.new
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def new_url
    @new_url ||= Url.new
  end
end

app/helpers/hits_helper.rb
module HitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
    current_user
  end

  def admin?
    if logged_in?
     current_user.role == "admin"
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def check_if_admin
    if admin?
      render template: 'administrator/show.html.erb'
    else
      redirect_to root_path
      flash[:danger] = "You do not have access to the Admin page"
    end
  end
end

app/helpers/urls_helper.rb
module UrlsHelper

    def router
      url = Url.find_by(shortened_path: params[:path])
      if url
        save_hit_details url
        redirect_to "#{url.url}"
      else
        flash[:danger] = "Uh oh. #{Rails.application.secrets.app_url}/#{params[:path]} seems to be an invalid url."
        redirect_to root_path
      end
    end

    private

    def url_params
      params.require(:url).permit(:id, :url, :user_id)
    end

    def finnesse_url url
      url = ((url[/\Ahttp:\/\//] || url[/\Ahttps:\/\//]) ? url : "http://#{url}") if !url.nil? || !url.empty?
      url
    end

    def generate_shortened_path
      current_plan = @current_user.nil? ? "f" : "e"
      @url.shortened_path = current_plan + @url.id.to_s
      @url.save
    end

    def save_hit_details url
      hit = url.hits.new
      hit.ip_address = request.remote_ip
      hit.referrer = session[:referrer] || ""
      hit.city = request.location.data["city"]
      hit.zipcode = request.location.data["zipcode"]
      hit.country = request.location.data["country_name"]
      hit.save
    end

    def full_url url
      Rails.env.production? ? "#{Rails.application.secrets.app_url}/#{url.shortened_path}" : "#{Rails.application.secrets.app_url}:#{request.port}/#{url.shortened_path}"
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hits/index.html.erb
      <%= render "users/user_sidebar" %>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">History</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-8">
                  <%= render "layouts/chart" %>
                </div>
                <div class="col-lg-4">
                  <%= render "layouts/new_url" %>
                </div>
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Registered urls
                        </div>
                        <%= render :layout => "layouts/table" do %>
                        <tr class="odd gradeX">
                            <td>Trident</td>
                            <td>Internet Explorer 4.0</td>
                            <td>Win 95+</td>
                            <td class="center">4</td>
                            <td class="center">X</td>
                        </tr>
                        <tr class="even gradeC">
                            <td>Trident</td>
                            <td>Internet Explorer 5.0</td>
                            <td>Win 95+</td>
                            <td class="center">5</td>
                            <td class="center">C</td>
                        </tr>
                        <tr class="odd gradeA">
                            <td>Trident</td>
                            <td>Internet Explorer 5.5</td>
                            <td>Win 95+</td>
                            <td class="center">5.5</td>
                            <td class="center">A</td>
                        </tr>
                        <tr class="even gradeA">
                            <td>Trident</td>
                            <td>Internet Explorer 6</td>
                            <td>Win 98+</td>
                            <td class="center">6</td>
                            <td class="center">A</td>
                        </tr>
                        <tr class="odd gradeA">
                            <td>Trident</td>
                            <td>Internet Explorer 7</td>
                            <td>Win XP SP2+</td>
                            <td class="center">7</td>
                            <td class="center">A</td>
                        </tr>
                        <tr class="even gradeA">
                            <td>Trident</td>
                            <td>AOL browser (AOL desktop)</td>
                            <td>Win XP</td>
                            <td class="center">6</td>
                            <td class="center">A</td>
                        </tr>
                        <tr class="gradeA">
                            <td>Gecko</td>
                            <td>Firefox 1.0</td>
                            <td>Win 98+ / OSX.2+</td>
                            <td class="center">1.7</td>
                            <td class="center">A</td>
                        </tr>

                        <% end %>
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

app/views/layouts/_chart.html.erb
<% chart_id ||= "morris_chart"; x_key ||= "time"; y_keys ||= "hits"; y_labels ||= "Hit"; %>
<div class="panel panel-default">
    <div class="panel-heading">
        Hits over time
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div id="myfirstchart" style="height: 250px;"></div>
        <div id="morris-area-chart"></div>
    </div>
    <!-- /.panel-body -->
</div>
<!-- /.panel -->

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>

        new Morris.Line({
          // ID of the element in which to draw the chart.
          element: "<%= chart_id %>",
          // Chart data records -- each entry in this array corresponds to a point on
          // the chart.
          data: [
            <%= yield %>
          ],
          // The name of the data record attribute that contains x-values.
          xkey: "<%= x_key %>",
          // A list of names of data record attributes that contain y-values.
          ykeys: ["<%= y_keys %>"],
          // Labels for the ykeys -- will be displayed when you hover over the
          // chart.
          labels: ["<%= y_labels %>"]
        });

    $(document).ready(function() {
    });
    </script>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert fade in alert-<%= message_type %> container">
    <button class="close" data-dismiss="alert">&times;</button>
  	<div class="show-flash" data-message="<%= message %>"><%= message.html_safe || message %></div>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer green-bg bottom-pad">
  <p class="text-center">&copy; 2015 (R) Lycent Url Shortener corporation. All Rights Reserved</p>
</footer>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top green-bg" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, :class=>"navbar-brand pad-5 header-nav" do %>
          <!-- <i class="fa fa-cloud-download fa-2x"></i> -->
          <%= image_tag "lycent-icon1.png", :class=>"img-logo" %>
          <span class="header-text">Lycent</span>
        <% end %>
    </div>
    <!-- /.navbar-header -->
<div class="navbar-collapse collapse">
    <ul class="nav navbar-top-links navbar-right header-nav">
      <!-- nav new url form -->
        <li><%= render "layouts/url_form_in_navbar" %></li>
      <!-- nav new url form -->
      <li><a href="/">Home</a></li>
      <li class="divider-vertical"></li>
      <li><a href="#">About</a></li>
      <!-- /input-group -->
      <% if current_user %>
        <li>
          <%= link_to user_path(current_user) do %>
            <i class="fa fa-user fa-fw"></i>&nbsp;My dashboard
          <% end %>
        </li>

        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>
                <%= "#{current_user.first_name} logged in"%>
                <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                  <%= link_to user_path(current_user) do %>
                    <i class="fa fa-user fa-fw"></i>&nbsp;My dashboard
                  <% end %>
                </li>

                <li class="divider"></li>
                <li><%= link_to logout_path do %>
                    <i class="fa fa-sign-out fa-fw"></i>Logout
                    <% end %>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
        <% else %>
        <li>
          <%= link_to "Login | Sign Up", login_path %>
        </li>

      <% end %>
    </ul>
    <!-- /.navbar-top-links -->
  </div><!-- / .div.collapse -->
</nav>
<%= render_breadcrumbs(" / ", { class: 'no-margin-bottom', active_class: 'active' }) %>
<%= render "layouts/flash" %>

app/views/layouts/_new_url.html.erb
<% new_url %>
<div class="row" >
  <div class="well col-lg-12">
    <%= form_for @new_url, html: { :role => "form" } do |f| %>
       <div class="col-lg-10 lead form-group no-bottom">
         <%= f.label :url, "Shorten a url:", :class=>"pull-left text-right col-md-3" %>
         <div class="form-group input-group">
           <span class="input-group-addon">http://</span>
           <%= f.text_field :url, { :class => "form-control", :placeholder => "www.example.com" } %>
         </div>
       </div>
       <%=f.submit "Shorten", :class=>"btn btn-md btn-success left" do %>
         <i class="fa fa-send"></i>&nbsp;Shorten
       <% end %>
   <% end %>
  </div>
</div>

app/views/layouts/_new_url_large.html.erb
<% new_url %>
<div class="row" >
  <div class="well col-lg-12">
    <%= form_for @new_url, html: { :role => "form" }, remote: true do |f| %>
       <div class="lead form-group no-bottom">
         <div class="form-group input-group">
           <span class="input-group-addon"><i class="fa fa-bolt"></i></span>
           <%= f.text_field :url, { :class => "form-control input-lg", :placeholder => "Paste long url here" } %>
           <span class="input-group-btn">
             <%= button_tag(type: 'submit',  class: "btn btn-lg btn-default navbar-form-submit", id: 'new_url' ) do %>
               <i class="fa fa-send"></i>&nbsp;Shorten
             <% end %>
           </span>
         </div>
       </div>
   <% end %>
  </div>
</div>

app/views/layouts/_notice_card.html.erb
<div class="col-md-12">
  <% color ||= "green"; icon ||= "tasks"; comment ||= "Total visits"; count ||= 0 %>
    <div class="panel panel-<%= color %>">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-3">
                    <i class="fa fa-<%= icon %> fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                    <div class="huge"><%= count %></div>
                    <div><%= comment %></div>
                </div>
            </div>
        </div>
        <a href="#">
            <div class="panel-footer">
                <span class="pull-left">View Details</span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
            </div>
        </a>
    </div>
</div>

app/views/layouts/_table.html.erb
<% table_id ||= "lycent-dataTables" %>
<!-- /.panel-heading -->
<div class="panel-body">
    <div class="dataTable_wrapper">
        <table class="table table-striped table-bordered table-hover" id="<%= table_id %>">

              <%= yield %>

        </table>
    </div>
    <!-- /.table-responsive -->

</div>
<!-- /.panel-body -->

<script>

    $("#<%= table_id || 'lycent-dataTables' %>").DataTable({
            responsive: true
    });

</script>

app/views/layouts/_url_form_in_navbar.html.erb
<% new_url %>
<%= form_for @new_url, html: { :class=>"navbar-form", :role=>"form" } do |f| %>
  <div class="input-group">
    <%= f.text_field :url, { :class => "form-control navbar-form-url", :placeholder => "www.longurl.com..." } %>
    <span class="input-group-btn">
      <%= button_tag(type: 'submit', class: "btn  btn-default navbar-form-submit", id: 'new_url')  do %>
        <i class="fa fa-send"></i>
      <% end %>
    </span>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lycent" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div id="wrapper">
      <%= render "layouts/navbar" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/urls/_url.html.erb
<% url ||= {} %>
<li class="url-item">
<div class="row">
  <div class="col-md-1 side-img">
    <i class="fa fa-link"></i>
  </div>
   <div class="col-md-10">
     <%= link_to  "#{host_url}/#{url.shortened_path}", "#{host_url}/#{url.shortened_path}", :class=>"main-link clearfix" %>
     <%= link_to  "#{url.url}", "#{url.url}", :class=> "article-title smaller" %>
   </div>
   <div class="col-md-1">
     <%= link_to login_path do %>
       <i class="fa fa-bar-chart"></i>
     <% end %>
   </div>
</div>
</li>

app/views/urls/_url_details_table.html.erb
<%= render :layout => "layouts/table", :locals => { :table_id => "url_table" } do %>
<% if @url_hits && !@url_hits.empty? %>
    <thead>
      <tr>
        <th>S/N</th>
        <th>Visit from</th>
        <th>Ip address</th>
        <th>Location</th>
        <th>Zip code</th>
        <th>Time/Date</th>
      </tr>
    </thead>
    <tbody>
      <% count = 1; @url_hits.each do |hit| %>
        <tr class="odd gradeX">
            <td><%= count %></td>
            <td><%=link_to hit.referrer, hit.referrer %></td>
            <td><%= hit.ip_address %></td>
            <td><%= "#{hit.city}, #{hit.country}" %></td>
            <td class="center"><%= "#{hit.zipcode}" %></td>
            <td class="center"><%= "#{time_ago_in_words(hit.created_at, include_seconds: true)} ago\n#{hit.created_at.strftime("%a, %d %b %y")}" %></td>
        </tr>
      <% count += 1; end %>
    <% else %>
      <tr>
        This link hasn't been visited yet
      </tr>
    <% end %>
  </tbody>
<% end %>

app/views/urls/_urls_notice_cards.html.erb
<%= render "layouts/notice_card", :color=>"yellow", :icon=>"support", :count=>"#{@url_hits.size || 0}" %>
<%= render "layouts/notice_card", :comment=>"New hits", :count=>"#{@url_hits.size || 0}" %>

app/views/urls/create.js.erb
$("#shortened-url-list").prepend('<%=j render "urls/url", :url=>@url %>');
$("#url_url").val("<%= (((host_url || "") + '/' + @url.shortened_path) || "") %>");

app/views/urls/index.html.erb
    <div id="wrapper">
      <%= render "layouts/navbar" %>
      <%= render "users/user_sidebar" %>

        <div id="page-wrapper">
          <%= render "layouts/new_url" %>
          
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">History</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Registered urls
                        </div>
                        <%= render "layouts/table" %>
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->


    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>

        $('#dataTables-example').DataTable({
                responsive: true
        });

    $(document).ready(function() {
    });
    </script>

app/views/urls/shorten.html.erb
<div class="container">

   <div class="jumbo center">
    <!-- nav new url form -->
      <%= render "layouts/new_url_large" %>
    <!-- nav new url form -->
   </div>

   <!-- Example row of columns -->
   <div class="row">
     <div class="col-lg-10 col-lg-offset-1">
       <ul id="shortened-url-list" class="shortened-list-menu">
         <p class="separator text-center"><span>Recently shortened links</span></p>
         <%if @urls %>
           <% @urls.each do |url| %>
            <%= render "urls/url", :url => url  %>
           <% end %>
         <% end %>
       </ul>
     </div>
   </div>

 </div> <!-- /container -->

app/views/urls/show.html.erb
<%= render "users/user_sidebar" %>
  <div id="page-wrapper">
      <div class="row">
          <div class="col-lg-12">
              <h3 class="page-header"><%= @url.url if @url %></h3>
          </div>
          <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
      <div class="row">
          <div class="col-lg-8">
            <%= render :layout => "layouts/chart", :locals => {x_key: "days", y_keys: "hits", y_labels: "impact"} do %>
              <% @url_hits.each do %>
              { year: '2012', value: 20 }
              <% end %>
            <% end %>
          </div>
          <div class="col-lg-4">
            <%= render "urls_notice_cards" %>
          </div>
          <div class="col-lg-12">
              <div class="panel panel-default">
                  <div class="panel-heading">
                      Registered urls
                  </div>
                  <%= render "urls/url_details_table" %>
              <!-- /.panel -->

              </div>
              <!-- /.panel -->
          </div>
          <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
  </div>
  <!-- /#page-wrapper -->

app/views/users/_new_user_form.html.erb
<% @user = User.new %>
<div class="panel-body">
    <%= form_for(@user, html: { role: "form" }) do |f|%>
        <fieldset>
          <div class="form-group">
            <%= f.text_field :first_name,  { :class => "form-control", :placeholder => "first name" } %>
          </div>
            <div class="form-group">
              <%= f.text_field :email,  { :class => "form-control", :placeholder => "email" } %>
            </div>
            <div class="form-group">
              <%= f.text_field :username,  { :class => "form-control", :placeholder => "username" } %>
            </div>
            <div class="form-group">
              <%= f.password_field :password,  { :class => "form-control", :placeholder => "password" } %>
            </div>
            <div class="form-group">
              <%= f.password_field :password_confirmation,  { :class => "form-control", :placeholder => "confirm password" } %>
            </div>
            <!-- Change this to a button or input when using this as a form -->
            <%= f.submit "submit", :class=>"btn btn-lg btn-success btn-block" %>
        </fieldset>
    <% end %>
</div>

app/views/users/_user_login_form.html.erb
<div class="login-panel panel panel-default set-to-top">
    <div class="panel-heading">
        <h3 class="panel-title">Please Sign In</h3>
    </div>
    <div class="panel-body">
        <%= form_for(:session, url: login_path, html: { role: "form" }) do |f|%>
            <fieldset>
                <div class="form-group">
                  <%= f.text_field :email,  { :class => "form-control", :placeholder => "email" } %>

                </div>
                <div class="form-group">
                  <%= f.password_field :password,  { :class => "form-control", :placeholder => "password" } %>
                </div>
                <div class="checkbox">
                    <label>
                        <%= f.check_box :remember %>
                        Remember me
                    </label>
                </div>
                <!-- Change this to a button or input when using this as a form -->
                <%= f.submit "Login", :class => "btn btn-lg btn-success btn-block" %>
            </fieldset>
        <% end %>
    </div>
</div>

app/views/users/_user_notice_cards.html.erb
<div class="col-lg-4">
  <%= render "layouts/notice_card", :color=>"yellow", :icon=>"support", :count=>"#{@total_hits}", :comment=>"Referrals from other sites" %>
</div>
<div class="col-lg-4">
  <%= render "layouts/notice_card", :color=>"primary", :icon=>"tasks", :count=>"#{@total_hits}", :comment=>"Total visits" %>
</div>
<div class="col-lg-4">
  <%= render "layouts/notice_card", :color=>"green", :icon=>"send", :count=>"#{@current_user.urls_count || @user_urls.size}", :comment=>"Registered urls" %>
</div>